### ISSUE TITLE
Handling NaN townsend values

### ISSUE THREAD

**Issue by MattStammers** [LTHTR-DST/hdruk_avoidable_admissions#18]
We are currently losing 330 patients for whom Townsend cannot be calculated. How have you handled this?

**Comment by vvcb** [comment]
`townsend_score_decile.fillna(0)` is a workaround. `nan` is treated as float by Pandas. Modifying the schema to accept `float` instead of `int` dtypes to accomodate `nan` will make values like 3.5 valid as well.

This is documented in [the example pipeline](https://lthtr-dst.github.io/hdruk_avoidable_admissions/admitted_care_pipeline_example).

**Comment by MattStammers** [comment]
This one can be closed
