### ISSUE TITLE
Making edwaittime a nullable field

### ISSUE THREAD

**Issue by quindavies** [LTHTR-DST/hdruk_avoidable_admissions#32]
`edwaittime` currently fails validation as field not nullable - some records leave before being seen my clinician. This needs to be accounted for

**Comment by vvcb** [comment]
`edwaittime` and `timeined` are currently set to `int` data type which causes problems with `nan` values even though they are set to be nullable.

Is there another column that allows us to identify these patients who left before being seen?

I will talk you through submitting your first pull request tomorrow! Can you please do a little bit of reading around this?

**Comment by georgm8** [comment]
Quite a few of the columns in the EmergencyCareEpisodeSchema are both enforced to be of type ```np.int64``` and also specify ```nullable=True```. Because ```nan``` values are floats these validation rules are fighting each other in the case ```nan``` values exist in the data.

Pandas does now support a [Nullable integer data type](https://pandas.pydata.org/docs/user_guide/integer_na.html)

What do you think about applying the ```dtype=pd.Int64Dtype()``` to the schema? With the caveat that the Nullable integer data type is still 'experimental'
